[package]
name = "asterisk"
version = "0.1.0"
description = "An Multi-Agent AI Framework for 100x Productivity"
keywords = []
categories = []

include = ["/src", "README.md", "LICENSE"]
license = "Apache-2.0"
readme = "README.md"
edition = "2021"
rust-version = "1.67"
documentation = "https://docs.rs/asterisk"
repository = "https://github.com/appcypher/asterisk"
authors = ["Stephen Akinyemi <appcypher@outlook.com>"]

[lib]
path = "src/lib.rs"
doctest = true

[[bin]]
name = "asterisk"
path = "src/main.rs"
doc = false

[dependencies]
anyhow = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"

[features]
default = []

[metadata.docs.rs]
all-features = true
# defines the configuration attribute `docsrs`
rustdoc-args = ["--cfg", "docsrs"]
#
# See https://doc.rust-lang.org/cargo/reference/profiles.html for more info.
# [profile.release]
# Do not perform backtrace for panic on release builds.
## panic = 'abort'
# Perform optimizations on all codegen units.
## codegen-units = 1
# Tell `rustc` to optimize for small code size.
## opt-level = "s" # or 'z' to optimize "aggressively" for size
# Enable link time optimization.
## lto = true
# Amount of debug information.
# 0/false: no debug info at all; 1: line tables only; 2/true: full debug info
## debug = false
# Strip debug symbols
## strip = "symbols"

# Speedup build on macOS
# See https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html#splitting-debug-information
[profile.dev]
split-debuginfo = "unpacked"
